# Generated by Django 4.2.30 on 2026-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='resolution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
